// Ported verbatim from the storefront src/data/products.js (approved catalogue).
// 3 categories, 36 products: 6 tail lifts, 13 trailer parts, 17 accessories.
// price: null = enquiry-only / POA.

export const CATEGORIES = [
  { slug: "tail-lifts", name: "Tail Lifts", tag: "Built to order", blurb: "Sized for Aussie bodies. 1.5T to 3T aluminium and steel, 24V, full kit included." },
  { slug: "trailer-parts", name: "Trailer Parts", tag: "Enquiry only", blurb: "Door gear, hinges, tracks, canvas stands and columns. Call for fitment and price." },
  { slug: "accessories", name: "Accessories", tag: "VIC stock", blurb: "Bars, buffers, bolts, boxes, handles and fittings for bodies and trailers." },
];

export const PRODUCTS = [
  // ── Tail Lifts (6) ──
  { sku: "TL-20-2450-2400", name: "Hydraulic Tail Lift 2T Aluminium W2450xH2400 24V", category: "tail-lifts", sub: "Tail Lifts", price: 4450, brand: "Beauway", rating: 4.8, reviews: 12, badge: "2T Aluminium", fit: "Suits rigid trucks and tray bodies", oem: "BW-TL-20-2400", status: "Built to order", lead: "3 to 4 weeks", desc: "2-tonne aluminium hydraulic tail lift, W2450xH2400, 24V with zinc-nickel cylinders, safety valves and galvanized bracket. Includes warning light, anti-slip plate, foot controller, seal kit and locking latch.", specs: { Capacity: "2000 kg", Platform: "2450 W x 2400 H mm", Power: "24V", Material: "Aluminium", Finish: "Anti slip plate" } },
  { sku: "TL-20-2450-2200", name: "Hydraulic Tail Lift 2T Aluminium W2450xH2200 24V", category: "tail-lifts", sub: "Tail Lifts", price: 4250, brand: "Beauway", rating: 4.8, reviews: 8, badge: "2T Aluminium", fit: "Suits rigid trucks and tray bodies", oem: "BW-TL-20-2200", status: "Built to order", lead: "3 to 4 weeks", desc: "2-tonne aluminium hydraulic tail lift, W2450xH2200, 24V with zinc-nickel cylinder, safety valve and galvanized bracket. Includes warning light, anti-slip plate, foot controller, seal kit and locking latch.", specs: { Capacity: "2000 kg", Platform: "2450 W x 2200 H mm", Power: "24V", Material: "Aluminium", Finish: "Anti slip plate" } },
  { sku: "TL-20-2450-2600", name: "Hydraulic Tail Lift 2T Aluminium W2450xH2600 24V", category: "tail-lifts", sub: "Tail Lifts", price: 4650, brand: "Beauway", rating: 4.8, reviews: 10, badge: "2T Aluminium", fit: "Suits rigid trucks and tray bodies", oem: "BW-TL-20-2600", status: "Built to order", lead: "3 to 4 weeks", desc: "2-tonne aluminium hydraulic tail lift, W2450xH2600, 24V with zinc-nickel cylinders, safety valves and galvanized bracket. Includes warning light, anti-slip plate, foot controller, seal kit and locking latch.", specs: { Capacity: "2000 kg", Platform: "2450 W x 2600 H mm", Power: "24V", Material: "Aluminium", Finish: "Anti slip plate" } },
  { sku: "TL-15-2450-2400", name: "Hydraulic Tail Lift 1.5T Aluminium W2450xH2400 24V", category: "tail-lifts", sub: "Tail Lifts", price: 3850, brand: "Beauway", rating: 4.7, reviews: 6, badge: "1.5T Aluminium", fit: "Suits light rigids and vans", oem: "BW-TL-15-2400", status: "Built to order", lead: "3 to 4 weeks", desc: "1.5-tonne aluminium hydraulic tail lift, W2450xH2400, 24V with zinc-nickel cylinders, safety valves and galvanized bracket. Includes warning light, anti-slip plate, foot controller, seal kit and locking latch.", specs: { Capacity: "1500 kg", Platform: "2450 W x 2400 H mm", Power: "24V", Material: "Aluminium", Finish: "Anti slip plate" } },
  { sku: "TL-30-2450-2600-S", name: "Hydraulic Tail Lift 3T Steel W2450xH2600 24V", category: "tail-lifts", sub: "Tail Lifts", price: 5900, brand: "Beauway", rating: 4.9, reviews: 5, badge: "3T Steel", fit: "Suits heavy rigids and fleet bodies", oem: "BW-TL-30-2600", status: "Built to order", lead: "4 to 5 weeks", desc: "3-tonne steel hydraulic tail lift, W2450xH2600, 24V with zinc-nickel cylinders, safety valves and galvanized bracket. Includes warning light, anti-slip plate, foot controller, seal kit and locking latch.", specs: { Capacity: "3000 kg", Platform: "2450 W x 2600 H mm", Power: "24V", Material: "Steel", Finish: "Galv plus anti slip" } },
  { sku: "PU-12V-22KW", name: "Hydraulic Power Unit 12V 2.2kW c/w Accessories", category: "tail-lifts", sub: "Power Units", price: 790, brand: "Beauway", rating: 4.7, reviews: 4, badge: "Power Unit", fit: "Suits tail lift systems", oem: "BW-PU-12V", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Hydraulic power unit 12V 2.2kW complete with accessories for tail lift operation.", specs: { Voltage: "12V", Power: "2.2 kW", Use: "Tail lift spare", Inclusions: "Accessories kit" } },

  // ── Trailer Parts (13) — enquiry-only / POA ──
  { sku: "GL-11113", name: "27mm Steel Door Locking Gear 200L+200R", category: "trailer-parts", sub: "Door Gear", price: null, brand: "Ganland", rating: 4.7, reviews: 30, badge: "Door Gear", fit: "Suits truck and trailer doors", oem: "GL-11113", status: "Enquiry", lead: "Confirm stock", desc: "27mm steel door locking gear set, 200 left + 200 right.", specs: { Bar: "27 mm steel", Set: "200L plus 200R", Use: "Pantech rear doors" } },
  { sku: "GL-11113-NL", name: "27mm Steel Door Locking Gear without Latch", category: "trailer-parts", sub: "Door Gear", price: null, brand: "Ganland", rating: 4.6, reviews: 14, badge: "Door Gear", fit: "Suits truck and trailer doors", oem: "GL-11113-NL", status: "Enquiry", lead: "Confirm stock", desc: "27mm steel door locking gear without latch.", specs: { Bar: "27 mm steel", Latch: "Not included", Use: "Replacement bars" } },
  { sku: "GL-11113S", name: "27mm Stainless Steel Truck Door Gear 50L+50R", category: "trailer-parts", sub: "Door Gear", price: null, brand: "Ganland", rating: 4.8, reviews: 16, badge: "Stainless", fit: "Suits truck doors and marine", oem: "GL-11113S", status: "Enquiry", lead: "Confirm stock", desc: "27mm stainless steel truck door gear, 50 left + 50 right.", specs: { Bar: "27 mm stainless", Set: "50L plus 50R", Use: "Marine and food grade" } },
  { sku: "GL-13112", name: "Steel Hinges", category: "trailer-parts", sub: "Hinges", price: null, brand: "Ganland", rating: 4.6, reviews: 41, badge: "Hinge", fit: "Suits trailer doors and bodies", oem: "GL-13112", status: "Enquiry", lead: "Confirm stock", desc: "Steel hinges for trailer doors and body panels.", specs: { Material: "Steel", Use: "Doors and gates", Finish: "Zinc" } },
  { sku: "GL-13198B", name: "Steel Hinges", category: "trailer-parts", sub: "Hinges", price: null, brand: "Ganland", rating: 4.6, reviews: 25, badge: "Hinge", fit: "Suits trailer doors and bodies", oem: "GL-13198B", status: "Enquiry", lead: "Confirm stock", desc: "Steel hinges for trailer doors and body panels.", specs: { Material: "Steel", Use: "Tailgates", Finish: "Zinc" } },
  { sku: "A02-01S-01", name: "Side Door Hinge Stainless 304 Polished", category: "trailer-parts", sub: "Hinges", price: null, brand: "Caiyuan", rating: 4.7, reviews: 22, badge: "304 Stainless", fit: "Suits truck side doors", oem: "A02-01S-01", status: "Enquiry", lead: "Confirm stock", desc: "Side door hinge, stainless steel 304, polished.", specs: { Material: "304 stainless", Finish: "Polished", Use: "Side doors" } },
  { sku: "GL-19113H1", name: "Steel Q Track 4.5m", category: "trailer-parts", sub: "Tracks", price: null, brand: "Ganland", rating: 4.7, reviews: 23, badge: "Q Track", fit: "Suits curtains and load restraint", oem: "GL-19113H1", status: "Enquiry", lead: "Confirm stock", desc: "Steel Q track, 4.5m per piece.", specs: { Length: "4.5 m", Material: "Steel", Use: "Load restraint" } },
  { sku: "GL-19113SH1", name: "304 Stainless Steel Q Track 4.5m", category: "trailer-parts", sub: "Tracks", price: null, brand: "Ganland", rating: 4.8, reviews: 12, badge: "304 Stainless", fit: "Suits curtains and marine", oem: "GL-19113SH1", status: "Enquiry", lead: "Confirm stock", desc: "304 stainless steel Q track, 4.5m per piece.", specs: { Length: "4.5 m", Material: "304 stainless", Use: "Washdown trailers" } },
  { sku: "GL-19111H1", name: "Steel F Track 3050x132x2mm", category: "trailer-parts", sub: "Tracks", price: null, brand: "Ganland", rating: 4.7, reviews: 15, badge: "F Track", fit: "Suits curtains and decks", oem: "GL-19111H1", status: "Enquiry", lead: "Confirm stock", desc: "Steel F track 3050x132x2mm, 4.5m per piece.", specs: { Length: "3050 mm", Profile: "F track", Material: "Steel" } },
  { sku: "F07-04C-01", name: "Iron Column Zinc Plated", category: "trailer-parts", sub: "Structure", price: null, brand: "Caiyuan", rating: 4.6, reviews: 9, badge: "Column", fit: "Suits curtains and bodies", oem: "F07-04C-01", status: "Enquiry", lead: "Confirm stock", desc: "Iron column, steel, zinc plated, built to drawing.", specs: { Material: "Iron", Finish: "Zinc plated", Use: "Body upright" } },
  { sku: "CANVAS-1995-1600", name: "Canvas Stand 1995Wx1600H Steel Powder Coated", category: "trailer-parts", sub: "Canvas Stands", price: null, brand: "Caiyuan", rating: 4.6, reviews: 7, badge: "Canvas Stand", fit: "Suits tautliner bodies", oem: "CANVAS-1995", status: "Built to order", lead: "2 to 3 weeks", desc: "Canvas stand 1995W x 1600H, steel, powder coated, built to drawing.", specs: { Width: "1995 mm", Height: "1600 mm", Finish: "Powder coated" } },
  { sku: "CANVAS-2045-1600", name: "Canvas Stand 2045Wx1600H Steel Powder Coated", category: "trailer-parts", sub: "Canvas Stands", price: null, brand: "Caiyuan", rating: 4.6, reviews: 6, badge: "Canvas Stand", fit: "Suits tautliner bodies", oem: "CANVAS-2045", status: "Built to order", lead: "2 to 3 weeks", desc: "Canvas stand 2045W x 1600H, steel, powder coated, built to drawing.", specs: { Width: "2045 mm", Height: "1600 mm", Finish: "Powder coated" } },
  { sku: "CANVAS-1250-1600", name: "Canvas Stand 1250Wx1600H Steel Powder Coated", category: "trailer-parts", sub: "Canvas Stands", price: null, brand: "Caiyuan", rating: 4.6, reviews: 6, badge: "Canvas Stand", fit: "Suits tautliner bodies", oem: "CANVAS-1250", status: "Built to order", lead: "2 to 3 weeks", desc: "Canvas stand 1250W x 1600H, steel, powder coated, built to drawing.", specs: { Width: "1250 mm", Height: "1600 mm", Finish: "Powder coated" } },

  // ── Accessories (17) ──
  { sku: "GL-15616", name: "Steel Cargo Bar with Handle", category: "accessories", sub: "Load Restraint", price: 129, brand: "Ganland", rating: 4.7, reviews: 26, badge: "Cargo Bar", fit: "Suits pantech vans and trailers", oem: "GL-15616", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Steel cargo bar with handle for load control.", specs: { Material: "Steel", Use: "Pantech and trailers", Type: "Cargo bar" } },
  { sku: "GL-23116", name: "Rubber Buffer", category: "accessories", sub: "Buffers", price: 12.5, brand: "Ganland", rating: 4.6, reviews: 31, badge: "Buffer", fit: "Suits doors and tailgates", oem: "GL-23116", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Rubber buffer for doors and tailgates.", specs: { Material: "Rubber", Use: "Doors" } },
  { sku: "GL-ASJ04", name: "Steel Spring Bolt", category: "accessories", sub: "Bolts", price: 14.5, brand: "Ganland", rating: 4.6, reviews: 29, badge: "Spring Bolt", fit: "Suits doors and gates", oem: "GL-ASJ04", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Steel spring bolt for doors and gates.", specs: { Material: "Steel", Type: "Spring bolt" } },
  { sku: "GL-19120", name: "Steel End Fitting with Strap", category: "accessories", sub: "Fittings", price: 26, brand: "Ganland", rating: 4.6, reviews: 18, badge: "End Fitting", fit: "Suits curtains and straps", oem: "GL-19120", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Steel end fitting with strap.", specs: { Use: "Curtains", Type: "End fitting" } },
  { sku: "GL-19117", name: "Steel End Fitting with Strap", category: "accessories", sub: "Fittings", price: 24, brand: "Ganland", rating: 4.6, reviews: 16, badge: "End Fitting", fit: "Suits curtains and straps", oem: "GL-19117", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Steel end fitting with strap.", specs: { Use: "Curtains", Type: "End fitting" } },
  { sku: "GL-16513", name: "Steel Door Retainer", category: "accessories", sub: "Door Hardware", price: 45, brand: "Ganland", rating: 4.6, reviews: 13, badge: "Retainer", fit: "Suits truck and trailer doors", oem: "GL-16513", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Steel door retainer for truck and trailer doors.", specs: { Material: "Steel", Use: "Hold open" } },
  { sku: "GL-25126", name: "Steel Tool Box 1200x450x400", category: "accessories", sub: "Tool Boxes", price: 293, brand: "Ganland", rating: 4.8, reviews: 21, badge: "Steel Box", fit: "Suits ute trays and trailer drawbars", oem: "GL-25126", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Steel toolbox 1200x450x400 for utes, trays and trailers.", specs: { Size: "1200 x 450 x 400 mm", Material: "Steel", Lock: "Lockable lid" } },
  { sku: "A20-01S-06", name: "DN16 Paddle Handle Latch 304 Stainless Polished", category: "accessories", sub: "Latches", price: 23, brand: "Caiyuan", rating: 4.7, reviews: 18, badge: "304 Stainless", fit: "Suits toolboxes and side doors", oem: "A20-01S-06", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "DN16mm paddle handle latch, 304 stainless steel, polished, built to drawing.", specs: { Material: "304 stainless", Type: "Paddle latch" } },
  { sku: "GL-12140", name: "Zinc Alloy Lock", category: "accessories", sub: "Locks", price: 17.5, brand: "Ganland", rating: 4.6, reviews: 33, badge: "Lock", fit: "Suits toolboxes and canopies", oem: "GL-12140", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Zinc alloy lock with keys for toolboxes and panels.", specs: { Material: "Zinc alloy", Keys: "Included" } },
  { sku: "GL-14175", name: "Stainless Steel Handle", category: "accessories", sub: "Handles", price: 11, brand: "Ganland", rating: 4.6, reviews: 27, badge: "Stainless", fit: "Suits toolboxes and doors", oem: "GL-14175", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Stainless steel pull handle for toolboxes and doors.", specs: { Material: "Stainless", Use: "Doors" } },
  { sku: "GL-14175B", name: "Steel Handle L330 H50 without Mounting Base", category: "accessories", sub: "Handles", price: 11, brand: "Ganland", rating: 4.5, reviews: 19, badge: "Steel", fit: "Suits toolboxes and doors", oem: "GL-14175B", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Steel handle L330 H50 without mounting base.", specs: { Length: "330 mm", Material: "Steel" } },
  { sku: "GL-13213", name: "228mm Steel Hinges", category: "accessories", sub: "Hinges", price: 10, brand: "Ganland", rating: 4.6, reviews: 20, badge: "228mm", fit: "Suits doors and tailgates", oem: "GL-13213", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "228mm steel hinges for doors and tailgates.", specs: { Length: "228 mm", Material: "Steel" } },
  { sku: "GL-13195S", name: "235mm 304 Stainless Steel Hinges", category: "accessories", sub: "Hinges", price: 16, brand: "Ganland", rating: 4.8, reviews: 17, badge: "304 Stainless", fit: "Suits doors and marine bodies", oem: "GL-13195S", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "235mm 304 stainless steel hinges.", specs: { Length: "235 mm", Material: "304 stainless" } },
  { sku: "GL-16511S", name: "Stainless Steel Retainer", category: "accessories", sub: "Door Hardware", price: 23, brand: "Ganland", rating: 4.7, reviews: 15, badge: "Stainless", fit: "Suits doors and panels", oem: "GL-16511S", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Stainless steel retainer for doors and panels.", specs: { Material: "Stainless", Use: "Hold open" } },
  { sku: "GL-19116", name: "Plastic End Cap", category: "accessories", sub: "Caps", price: 4.5, brand: "Ganland", rating: 4.5, reviews: 24, badge: "End Cap", fit: "Suits tracks and rails", oem: "GL-19116", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Plastic end cap for tracks and rails.", specs: { Material: "Plastic", Use: "Track ends" } },
  { sku: "GL-19116B", name: "Plastic End Cap", category: "accessories", sub: "Caps", price: 5.5, brand: "Ganland", rating: 4.5, reviews: 22, badge: "End Cap", fit: "Suits tracks and rails", oem: "GL-19116B", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Plastic end cap variant for tracks and rails.", specs: { Material: "Plastic", Use: "Track ends" } },
  { sku: "FZ-26184", name: "Roller", category: "accessories", sub: "Rollers", price: 32, brand: "Ganland", rating: 4.5, reviews: 11, badge: "Roller", fit: "Suits trailers and workshop", oem: "FZ-26184", status: "In stock VIC", lead: "Ships in 24 hrs", desc: "Roller for trailer and workshop use.", specs: { Use: "Trailers", Type: "Roller" } },
];

export const PROMOS = [
  { code: "WELCOME10", label: "First order", pct: 10, active: true },
  { code: "FLEET5", label: "5 plus units", pct: 5, active: false },
];

export const SETTINGS = {
  key: "store",
  storeName: "Aurex Truck Parts Australia",
  phone: "03 9000 0000",
  email: "sales@aurex.com.au",
  address: "Campbellfield, VIC 3061",
  hours: "Mon to Fri 8am to 5pm AEST",
  freeFreightOver: 500,
  standardFee: 24,
  expressFee: 39,
  abn: "ABN 12 345 678 901",
  announcement: "Free road freight over $500. Order by 2pm for same day dispatch.",
};
